In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# #Checking Data & I dropped Missing Numbers for Question 5:

In [67]:
df = pd.read_csv('movie.csv')
print('Our variables', df.columns)

print('\n Our Genres', df['Genre'].unique())

Missing_Values = pd.DataFrame.isnull(df)
print('\n Missing values in our dataset:\n', pd.DataFrame.sum(Missing_Values))
#Dropping null values
df.dropna()

duplicates = df.duplicated().sum()
print("\nNumber of Duplicated Records:", duplicates)
#Dropping duplicates
df.drop_duplicates()

Our variables Index(['Genre', 'Rotten Tomatoes', 'IMDB', 'Audience Ratings', 'Budget_M',
       'Sales Revenue_M', 'Year of Release'],
      dtype='object')

 Our Genres ['Horror' 'Romance' 'SciFi' 'Action' 'Thriller' 'Comedy' 'Sci-Fi' 'Drama'
 'Documentary']

 Missing values in our dataset:
 Genre               0
Rotten Tomatoes     0
IMDB                0
Audience Ratings    0
Budget_M            0
Sales Revenue_M     5
Year of Release     0
dtype: int64

Number of Duplicated Records: 1

,Genre,Rotten Tomatoes,IMDB,Audience Ratings,Budget_M,Sales Revenue_M,Year of Release
0,Horror,125,5.0,3968,74.348337,31.356476,2020
1,Romance,84,9.8,8150,28.243154,212.016126,2013
2,SciFi,75,2.0,1040,164.601429,129.342033,2017
3,Action,68,7.9,6250,38.779734,424.519154,2019
4,Thriller,6,4.7,8356,102.752477,16.652313,2012
...,...,...,...,...,...,...,...
95,Action,116,7.7,2679,181.859900,302.058902,2006
96,SciFi,52,5.3,4950,163.289240,191.404030,2019
97,Thriller,67,7.1,2665,32.723478,447.692942,2002
98,Sci-Fi,61,6.5,3057,126150.789400,483.897336,1999
99,Horror,14,7.4,6838,80.288417,273.442451,1985

data_analysis = df.describe()
print(data_analysis)

for col in df.select_dtypes(include=['number']).columns:
    plt.figure(figsize=(8, 6))
    
    if col == 'Budget_M':
        # Applied log transformation to 'Budget_M as the scale kept forming a singular pillar'
        sns.histplot(np.log1p(df[col]), bins=20, kde=True)
        plt.title(f"Histogram and Density plot of Log({col})")
    else:
        sns.histplot(df[col], bins=20, kde=True)
        plt.title(f"Histogram and Density plot of {col}")

    plt.show()

# Question 1, Imputation Techniques Comparison:

In [69]:
#Mean Imputation 
meanimp = df.select_dtypes(include=['number']).columns
df[meanimp] = df[meanimp].fillna(df[meanimp].mean())
print(df[meanimp].describe())

#Median Imputation 
medianimp = df.select_dtypes(include=['number']).columns
df[medianimp] = df[medianimp].fillna(df[medianimp].median())
print(df[medianimp].describe())


#Mode imputation for a categorical column
mode_value = df['Year of Release'].mode()[0]
df['Year of Release'].fillna(mode_value, inplace=True)
print(df['Year of Release'].describe())

       Rotten Tomatoes        IMDB  Audience Ratings       Budget_M  \
count       101.000000  101.000000        101.000000     101.000000
mean         53.554455    5.562376       5272.663366    5456.333862
std          33.764323    2.608864       2891.578546   25371.661518
min           0.000000    1.100000        437.000000       3.274064
25%          26.000000    3.300000       2711.000000      48.764034
50%          52.000000    5.400000       5410.000000      92.511321
75%          77.000000    7.700000       7734.000000     155.704105
max         142.000000    9.900000       9882.000000  160159.381000

       Sales Revenue_M
count       101.000000
mean        239.422768
std         152.292526
min           6.018111
25%         120.709310
50%         214.397861
75%         365.354550
max         497.200395
       Rotten Tomatoes        IMDB  Audience Ratings       Budget_M  \
count       101.000000  101.000000        101.000000     101.000000
mean         53.554455    5.562376       5272.663366    5456.333862
std          33.764323    2.608864       2891.578546   25371.661518
min           0.000000    1.100000        437.000000       3.274064
25%          26.000000    3.300000       2711.000000      48.764034
50%          52.000000    5.400000       5410.000000      92.511321
75%          77.000000    7.700000       7734.000000     155.704105
max         142.000000    9.900000       9882.000000  160159.381000

       Sales Revenue_M
count       101.000000
mean        239.422768
std         152.292526
min           6.018111
25%         120.709310
50%         214.397861
75%         365.354550
max         497.200395
count      101
unique      45
top       1992
freq         6
Name: Year of Release, dtype: object

# Question 1: The impact of each technique of imputation does not appear signfiicant as most likely there is not enough errors in the data set that can change the mean,std, or values in the .describe() for the analysis, however, the missing values so it'll allow the variance to reduce and the distribution to be more uniformed, forming a more normal disbutrition, normally

# Question 2: Encoding catergorical variables

In [83]:
print('\n Our Genres', df['Genre'].unique())

df_onehot = pd.get_dummies(df, columns =['Genre'])

print(df_onehot)

 Our Genres ['Action' 'Comedy' 'Drama']
   Genre_Action  Genre_Comedy  Genre_Drama
0             1             0            0
1             0             1            0
2             0             0            1
3             1             0            0
4             0             1            0

# I use one-hot encoding as we didn't have many variables within our genres, however, I'm not sure if my code is right as it put it into 3 main genres rather than 7 different genres. One-hot encoding is more appropriate as order does not matter in our genres and it doesn't contain large sets of variables that can't be one-hot but rather, an example is freq encoding.